#!/bin/bash

action=$1
pending_dir=$4
postfix_master="$pending_dir/../postfix/etc/postfix/master.cf"
postfix_main="$pending_dir/../postfix/etc/postfix/main.cf"
app=__APP__
list_email=__LIST_EMAIL
install_dir=__INSTALL_DIR__
data_dir=__DATA_DIR__

[[ "$action" == "pre" ]] || exit 0

cat << EOF >> "$postfix_master"
# $app $list_email
$app   unix  -       n       n       -       -       pipe
    flags=ORhu user=$app argv=$install_dir/app/bin/mlmmj-receive -F -L $data_dir/\$nexthop
EOF 

sed -i "/^virtual_alias_maps = / s@\$@,hash:$install_dir/tables/virtual@" "$postfix_main"

if grep -q "^transport_maps = " "$postfix_main"; then
    # La ligne transport_maps existe, ajouter l'entrée à la fin
    if ! grep -q "hash:$install_dir/tables/transport" "$postfix_main"; then
        sed -i "/^transport_maps = / s@\$@,hash:$install_dir/tables/transport@" "$postfix_main"
    fi
else
    # La ligne transport_maps n'existe pas, l'ajouter
    echo "transport_maps = hash:$install_dir/tables/transport" >> "$postfix_main"
fi


# FIXME?

# Only deliver one message to Mlmmj at a time
#mlmmj_destination_recipient_limit = 1

