#!/bin/bash

action=$1
pending_dir=$4
postfix_master="$pending_dir/../postfix/etc/postfix/master.cf"
postfix_main="$pending_dir/../postfix/etc/postfix/main.cf"

if [ "$action" == "pre" ]; then
    echo -e "\n# MLMMJ mailing lists management made joyful\nmlmmj   unix  -       n       n       -       -       pipe\n    flags=ORhu user=mlmmj argv=/usr/local/bin/mlmmj-receive -F -L /var/spool/mlmmj/files/\n" >> "$postfix_master"
    sed -i "/^virtual_alias_maps = / s/$/,hash:\/var\/spool\/files\/virtual/" "$postfix_main"
    echo -e "\ntransport_maps = hash:/var/spool/mlmmj/tables/transport\n" >> "$postfix_main"
fi
