#!/bin/bash

action=$1
pending_dir=$4
postfix_master="$pending_dir/../postfix/etc/postfix/master.cf"
postfix_main="$pending_dir/../postfix/etc/postfix/main.cf"

[[ "$action" == "pre" ]] || exit 0
if ! grep -q "mlmmj.*mlmmj-receive" $postfix_master; then
    printf "\n# MLMMJ\nmlmmj   unix  -       n       n       -       -       pipe\n    flags=ORhu user=mlmmj argv=/usr/local/bin/mlmmj-receive -F -L /var/spool/mlmmj/files/\n" >> $postfix_master
fi

if ! grep -q "hash:/var/spool/mlmmj/tables/virtual" $postfix_main"; then
    sed -i "/^virtual_alias_maps = / s/$/,hash:\/var\/spool\/mlmmj\/tables\/virtual/" "$postfix_main"
fi
if ! grep -q "hash:/var/spool/mlmmj/tables/transport" /etc/postfix/main.cf; then
    printf "\ntransport_maps = hash:/var/spool/mlmmj/tables/transport\n" >> $postfix_main
fi
