#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DECLARE VARIABLES
#=================================================

app=$YNH_APP_INSTANCE_NAME
SPOOLDIR="/var/spool/mlmmj"
LISTNAME=$(ynh_app_setting_get --app=$app --key=list_name)
LISTDIR="$SPOOLDIR/$LISTNAME"
CRON_FILE="/etc/cron.d/$app"

#=================================================
# BACKUP DATA DIRECTORY
#=================================================

ynh_print_info --message="Backing up mlmmj list directory..."
ynh_backup --src_path="$LISTDIR"

#=================================================
# BACKUP CRON FILE
#=================================================

ynh_print_info --message="Backing up mlmmj cron file..."
ynh_backup --src_path="$CRON_FILE"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app."
