#!/bin/bash

#=================================================
# CONFIG
#=================================================

# Import YunoHost helpers
source /usr/share/yunohost/helpers
source _common.sh

ynh_abort_if_errors

# -------------------------------------------------------------
# Generic email list validator
# -------------------------------------------------------------

# Regex pour les adresses email
email_regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

validate__email_generic() {
    local email_list="$1"
    local invalid_emails=""
    while IFS= read -r email; do
        if [[ ! $email =~ $email_regex ]] && [[ ! -z "$email" ]]; then
            invalid_emails+="$email\n"
        fi
    done <<< "$email_list"

    if [[ ! -z "$invalid_emails" ]]; then
        echo -e "Invalid email addresses:\n$invalid_emails"
    fi
}

# -------------------------------------------------------------
# Validators
# -------------------------------------------------------------

validate__moderators() {
    validate__email_generic "$moderators"
}

validate__add() {
    validate__email_generic "$add"
}

validate__del() {
    validate__email_generic "$del"
}

# -------------------------------------------------------------
# Getters
# -------------------------------------------------------------

# General

get__list_status() {
    if [ -f "$control_dir/closedlist" ]; then
        echo "closedlist"
    elif [ -f "$control_dir/closedlistsub" ]; then
        echo "closedlistsub"
    else
        echo "open"
    fi
}

get__whocanpost() {
    if [ -f "$control_dir/modonlypost" ]; then
        echo "modonlypost"
    elif [ -f "$control_dir/subonlypost" ]; then
        echo "subonlypost"
    else
        echo "all"
    fi
}

# Owners


# Moderators

get__moderators() {
    if [ -f "$control_dir/moderators" ]; then
        cat "$control_dir/moderators"
    else
        echo ""
    fi
}

get__moderated() {
    if [ -f "$control_dir/moderated" ]; then
        echo "1"
    else
        echo "0"
    fi
}

get__moderation_mode() {
    if [ -f "$control_dir/modonlypost" ]; then
        echo "modonlypost"
    elif [ -f "$control_dir/subonlypost" ]; then
        echo "subonlypost"
    else
        echo "all"
    fi
}

# Sub

# Others


# -------------------------------------------------------------
# Setters
# -------------------------------------------------------------

# General

set__list_status() {
    case $list_status in
        "open")
            ynh_secure_remove "$control_dir/closedlistsub"
            ynh_secure_remove "$control_dir/closedlist"
            ynh_print_info "--message='List is open for subscription and unsubscription'"
            ;;

        "closedlistsub")
            touch "$control_dir/closedlistsub"
            ynh_secure_remove "$control_dir/closedlist"
            ynh_print_info "--message='List is closed for subscription'"
            ;;

        "closed_sub_unsub")
            touch "$control_dir/closedlist"
            ynh_secure_remove "$control_dir/closedlistsub"
            ynh_print_info "--message='List is closed for subscription and unsubscription'"
            ;;
    esac
}

set__whocanpost() {
    case $whocanpost in
        "all")
            ynh_secure_remove "$control_dir/subonlypost"
            ynh_secure_remove "$control_dir/modonlypost"
            ynh_print_info "--message='No moderation mode is set (all)'"
            ;;

        "subonlypost")
            touch "$control_dir/subonlypost"
            ynh_secure_remove "$control_dir/modonlypost"
            ynh_print_info "--message='Moderation mode set to subscribers only post'"
            ;;

        "modonlypost")
            touch "$control_dir/modonlypost"
            ynh_secure_remove "$control_dir/subonlypost"
            ynh_print_info "--message='Moderation mode set to moderators only post'"
            ;;
    esac
}

# Owners

# Moderation

set__moderated() {
    if [[ $moderated == 1 ]]; then
        touch "$control_dir/moderated"
        ynh_print_info "--message='Created $control_dir/moderated for moderated'"
    else
        ynh_secure_remove "$control_dir/moderated"
        ynh_print_info "--message='Removed $control_dir/moderated for moderated'"
    fi
}




# -------------------------------------------------------------
# Config apply
# -------------------------------------------------------------

ynh_app_config_run $1
