#!/bin/bash

#=================================================
# INSTALL
#=================================================

# Import YunoHost helpers
source /usr/share/yunohost/helpers
source _common.sh

# -------------------------------------------------------------
# Check name validity
# -------------------------------------------------------------

is_valid_listname() {
    # Check format
    if ! [[ $1 =~ ^[a-z0-9]+([.-][a-z0-9]+)*$ ]]; then
        ynh_print_err --message="Invalid mailing list name. It must be lowercase and can only contain letters, numbers, dots, and dashes."
        return 1
    fi

    # Check if name is a username
    if yunohost user list --output-as plain | grep -q "^$1$"; then
        ynh_print_err --message="The mailing list name '$1' is already in use as a username. Please choose a different name."
        return 1
    fi

    return 0
}

if ! is_valid_listname "$list_name"; then
    ynh_die --message="Validation failed for list name: $list_name"
fi

# -------------------------------------------------------------
# Install MLMMJ if necessary and check Postfix
# -------------------------------------------------------------

install_update_mlmmj "$REQUIRED_VERSION"

# -------------------------------------------------------------
# Mailing List Creation and Activation
# -------------------------------------------------------------

ynh_script_progression --message="Creating the list $list_name@$domain at $data_dir;"

#for DIR in incoming queue queue/discarded archive text subconf unsubconf \
#           bounce control moderation subscribers.d digesters.d requeue \
#           nomailsubs.d ynh
#do
#    mkdir -p "$install_dir/$DIR"
#done

owner=$(ynh_app_setting_get $app owner)
owner_email=$(yunohost user info "$owner" --output-as plain | grep 'mail:' | cut -d ' ' -f2)
echo "$owner_email" > "$data_dir/control/owner"
echo "$list_name@$domain" > "$data_dir/control/listaddress"

if [ -d "$lang_dir" ]; then
    cp "$lang_dir"/* "$data_dir/text"
fi

[ ! -d "$SPOOL_DIR" ] && mkdir -p "$SPOOL_DIR"
ln -s $data_dir $install_dir/$list_name
ln -s $data_dir $SPOOL_DIR/$list_name

# -------------------------------------------------------------
# Setting up conf files transport et virtual
# -------------------------------------------------------------

[ ! -d "$ETC_DIR" ] && mkdir -p "$ETC_DIR"

[ ! -f "$TRANSPORT_FILE" ] && touch "$TRANSPORT_FILE"
[ ! -f "$VIRTUAL_FILE" ] && touch "$VIRTUAL_FILE"

if ! grep -qF "$transport_entry" "$TRANSPORT_FILE"; then
    echo "$transport_entry" >> "$TRANSPORT_FILE"
    postmap "$TRANSPORT_FILE"
fi

if ! grep -qF "$virtual_entry" "$VIRTUAL_FILE"; then
    echo "$virtual_entry" >> "$VIRTUAL_FILE"
    postmap "$VIRTUAL_FILE"
fi

# -------------------------------------------------------------
# Symlinks for easier CLI administration
# -------------------------------------------------------------

if [ ! -d "$symlink_dir" ]; then
    mkdir -p "$symlink_dir"
fi
ln -s "$SPOOL_DIR" "$symlink_dir/$list_name"

# -------------------------------------------------------------
# Cron
# -------------------------------------------------------------

rand_min=$(shuf -i 0-59 -n 1) # Generate random minute execution (between 0 and 59)
if [ ! -d "$CRON_DIR" ]; then
    mkdir -p "$CRON_DIR"
    chmod 644 "$CRON_DIR"
fi
echo "$rand_min */2 * * * list $MLMMJMAINTD -F -L $data_dir" > "$cron_file" 

# -------------------------------------------------------------
# Default settings
# -------------------------------------------------------------

ynh_app_setting_set -a $app -k category -v "subscribers"
ynh_app_setting_set -a $app -k display_subscribers -v false
ynh_app_setting_set -a $app -k display_digesters -v false
ynh_app_setting_set -a $app -k display_nomailsubs -v false

touch "$control_dir/moderators"
touch "$control_dir/subonlypost"
echo "[$list_name]" > "$control_dir/prefix"
echo "postmaster@$domain" > "$control_dir/owner"
echo "postmaster@$domain" > "$data_dir/ynh/owner.txt"
touch "$control_dir/notifysub"
touch "$control_dir/subonlyget"
echo "postfix" > "$control_dir/verp"
touch "$control_dir/nodigestsub"
touch "$control_dir/nonomailsub"
echo "10485760" > "$control_dir/maxmailsize"  # 10MB
touch $data_dir/ynh/moderators.txt
touch $data_dir/ynh/submod.txt
touch $data_dir/ynh/subscribers.txt
touch $data_dir/ynh/digesters.txt
touch $data_dir/ynh/nomailsubs.txt

[ -f "../conf/footer_${language}.tpl" ] && footer_template="footer_${language}.tpl" || footer_template="footer_en.tpl"
ynh_add_config --template="$footer_template" --destination="$control_dir/footer"


# -------------------------------------------------------------
# Install completion
# -------------------------------------------------------------

ynh_script_progression --message="Mailing list $list_name@$domain was created successfully." --last
