#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

ynh_secure_remove --file="/etc/cron.d/$app"
ynh_secure_remove --file="/usr/share/yunohost/hooks/conf_regen/98-postfix_$app"
yunohost tools regen-conf postfix

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove "$app"
fi

ynh_remove_systemd_config

ynh_remove_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
