#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================

ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Count the number of mlmmj instances
mlmmj_instances=$(sudo yunohost app list | grep -c 'id: mlmmj')

# Remove mlmmj binaries and man pages only if this is the last instance
if [ "$mlmmj_instances" -eq 1 ]; then
    shopt -s nullglob

    dirbin="/usr/local/bin/"
    dirman="/usr/local/share/man/man1/"
    pattern="mlmmj-*"

    for file in "$dirbin$pattern"; do
        ynh_secure_remove --file="$file"
    done

    for file in "$dirman$pattern"; do
        ynh_secure_remove --file="$file"
    done

    ynh_secure_remove --file="/usr/local/share/mlmmj"
fi


# Remove the cron job
ynh_secure_remove --file="/etc/cron.d/$app"

# Remove the alias from /etc/aliases and regenerate aliases
if grep -q "^$LISTNAME:" /etc/aliases; then
    sed -i "/^$LISTNAME:/d" /etc/aliases
    newaliases
fi

# Remove other various files specific to the app
ynh_secure_remove --file="/etc/$app"
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
