#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

### This should be a symetric version of what happens in the install script

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    ynh_script_progression --message="Removing $app service integration..." --weight=1
    yunohost service remove "$app"
fi

ynh_secure_remove --file="$cron_file"
ynh_secure_remove --file="/usr/share/yunohost/hooks/conf_regen/98-postfix_$app"
yunohost tools regen-conf postfix

ynh_script_progression --message="Removal of $app completed" --last

# ============
# TODO / FIXME
# ============

# # -------------------------------------------------------------
# # Check for Remaining mlmmj Instances and Remove Binaries
# # -------------------------------------------------------------

# mlmmj_instances=$(sudo yunohost app list | grep -c 'id: mlmmj')

# # Remove mlmmj binaries and man pages only if this is the last remaining instance
# if [ "$mlmmj_instances" -eq 1 ]; then
#     shopt -s nullglob
#     dirbin="/usr/local/bin/"
#     dirman="/usr/local/share/man/man1/"
#     pattern="mlmmj-*"

#     rm -f /usr/local/bin/mlmmj-make-ml.sh
#     rm -f /usr/local/bin/mlmmj-recieve

#     for file in $dirbin$pattern; do
#         echo "Removing binary file: $file"
#         ynh_secure_remove --file="$file"
#     done

#     for file in $dirman$pattern; do
#         echo "Removing man page: $file"
#         ynh_secure_remove --file="$file"
#     done

#     ynh_secure_remove --file="/usr/local/share/mlmmj"
#     ynh_secure_remove --file="/usr/share/yunohost/hooks/conf_regen/98-postfix_mlmmj"


# fi
