#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..."

ynh_restore_file --origin_path="$install_dir"

chown -R "$app:$app" "$install_dir"

# #=================================================
# # RESTORE SYSTEM CONFIGURATIONS
# #=================================================

ynh_restore_file --origin_path="/etc/cron.d/$app"
ynh_restore_file --origin_path="/usr/share/yunohost/hooks/conf_regen/98-postfix_$app"
yunohost tools regen-conf postfix

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
