#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# -------------------------------------------------------------
# Download and compile MLMMJ and setup postfix tables
# -------------------------------------------------------------

ynh_script_progression "Building $app"

install_update_mlmmj

# -------------------------------------------------------------
# Setting up postfix with new transport and virtual tables
# -------------------------------------------------------------

ynh_script_progression "Configuring postfix"

ynh_config_add --template="regenconf_postfix" --destination="/usr/share/yunohost/hooks/conf_regen/98-postfix_$app"
YNH_HELPERS_VERSION=2 yunohost tools regen-conf postfix

# -------------------------------------------------------------
# Cron
# -------------------------------------------------------------

ynh_script_progression "Configuring Cron"

rand_min=$(shuf -i 0-59 -n 1) # Generate random minute execution (between 0 and 59)
echo "$rand_min */2 * * * $app $install_dir/app/bin/mlmmj-maintd -F -L $install_dir/list" > "/etc/cron.d/$app"

# -------------------------------------------------------------
# Upgrade completion
# -------------------------------------------------------------

ynh_script_progression "mlmmj upgrade completed."
